"""Generate the support matrix from real certification artifacts, never by hand.

certify_fleet runs every adapter against its target and returns structured results.
render_matrix_markdown and render_matrix_json turn those into the published matrix,
so the matrix cannot claim more than the gates actually proved.
"""

from __future__ import annotations

import os
import json
import shutil
import tempfile
from pathlib import Path

from .checks import certify, GateStatus
from ..registry import build_fleet, target_for


def _sample_of(a):
    if hasattr(a, "spec"):
        return a.spec.sample_dir
    return "langgraph" if "LangGraph" in a.framework else "llamaindex"


def certify_fleet():
    results = []
    for adapter, expected in build_fleet():
        tmp = Path(tempfile.mkdtemp()) / "proj"
        shutil.copytree(target_for(_sample_of(adapter)), tmp)
        cert = certify(adapter, str(tmp))
        npass = sum(1 for g in cert.gates if g.status == GateStatus.PASS)
        npend = sum(1 for g in cert.gates if g.status == GateStatus.PENDING_LIVE)
        nfail = sum(1 for g in cert.gates if g.status == GateStatus.FAIL)
        results.append({
            "framework": adapter.framework, "tier": cert.tier,
            "runtime": cert.runtime_status or "pending_live_host",
            "gates_pass": npass, "gates_pending_live": npend, "gates_fail": nfail,
            "language": getattr(adapter, "language", "python"),
            "native_package": adapter.native_package,
            "host_requirements": getattr(adapter, "host_requirements", ""),
        })
        shutil.rmtree(tmp.parent, ignore_errors=True)
    return results


def _provenance():
    import platform, subprocess, datetime, importlib.metadata as im
    def ver(pkg):
        try:
            return im.version(pkg)
        except Exception:
            return "not installed"
    sha = ""
    try:
        sha = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"],
                                      cwd=os.path.dirname(__file__),
                                      stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        sha = "unknown"
    return {
        "generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "tool_commit": sha,
        "python": platform.python_version(),
        "platform": platform.platform(),
        "framework_versions": {"langgraph": ver("langgraph"),
                               "llama-index-core": ver("llama-index-core")},
        "note": ("Native Certified rows ran their live gates here against the patched "
                 "project. Native Ready rows are source-patched with the live gates "
                 "pending a host that has the framework installed."),
    }


def render_matrix_json(results=None) -> str:
    results = results or certify_fleet()
    cert = sum(1 for r in results if r["tier"] == "Native Certified")
    ready = sum(1 for r in results if r["tier"] == "Native Ready")
    return json.dumps({"provenance": _provenance(),
                       "summary": {"native_certified": cert, "native_ready": ready,
                                   "total": len(results)}, "frameworks": results}, indent=2)


def render_matrix_markdown(results=None) -> str:
    results = results or certify_fleet()
    cert = sum(1 for r in results if r["tier"] == "Native Certified")
    ready = sum(1 for r in results if r["tier"] == "Native Ready")
    lines = []
    lines.append("# Vyrion native support matrix")
    lines.append("")
    lines.append("Generated by `vyrion certify` from live gate results. A row is "
                 "Native Certified only when the live gates (N13-N17) actually ran.")
    lines.append("")
    lines.append(f"{cert} Native Certified, {ready} Native Ready "
                 f"(non-live gates proven; live gates run on a host).")
    lines.append("")
    lines.append("| Framework | Tier | Gates pass | Live gates | Runtime proof |")
    lines.append("|---|---|---|---|---|")
    for r in results:
        live = "ran here" if r["runtime"] == "executed_here" else "pending host"
        lines.append(f"| {r['framework']} | {r['tier']} | "
                     f"{r['gates_pass']}/20 | {r['gates_pending_live']} pending | {live} |")
    lines.append("")
    lines.append("## Completing a Native Ready framework")
    lines.append("")
    lines.append("On a machine with the framework installed, run its live command "
                 "(shown by `vyrion certify --framework <name>`), capture the "
                 "transcript, and the same tool records the row as Native Certified.")
    lines.append("")
    lines.append("## Resistant control")
    lines.append("")
    lines.append("Temporal is tracked as a resistant control rather than a supported "
                 "target: its signal-with-payload resume does not expose the "
                 "approval-provenance gap the other frameworks share.")
    return "\n".join(lines)
